name: funbreak_vale_driver
description: "FunBreak Vale Driver App"
publish_to: 'none'

version: 1.4.0+50

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  cloud_firestore: ^6.1.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_sound: ^9.28.0
  path_provider: ^2.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFD700"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true
  ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/images/
    - assets/icons/
    - ios/Runner/Resources/notification.caf
